[tool.black]
line-length = 88
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
filter_files = true

[tool.semantic_release]
version_variables = ["setup.py:__version__"]